Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using AspNet_Projects.Extensions;
using AspNet_Projects.Models;


public class CartViewComponent : ViewComponent
{
    private Cart _cart;

    public CartViewComponent(Cart cart)
    {
        _cart = cart;
    }
    public IViewComponentResult Invoke()
    {
        return View(_cart);
    }
}

Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

public class MenuViewComponent : ViewComponent
{
    private List<MenuItem> _menuItems = new List<MenuItem>
        {
            new MenuItem{Controller="Home", Action="Index",Text="Lab 8"},
            new MenuItem{Controller="Product", Action="Index",Text="Каталог"},
            new MenuItem{IsPage=true, Area="Admin", Page="/Index", Text="Администрирование"}
        };

    public IViewComponentResult Invoke()
    {
        var controller = ViewContext.RouteData.Values["controller"];
        var page = ViewContext.RouteData.Values["page"];
        var area = ViewContext.RouteData.Values["area"];

        foreach (var item in _menuItems)
        {
            var _matchController = controller?.Equals(item.Controller) ?? false;
            var _matchArea = area?.Equals(item.Area) ?? false;
            if (_matchController || _matchArea)
            {
                item.Active = "active";
            }
        }
        return View(_menuItems);
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNet_Projects</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome-free-6.4.2-web/css/all.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNet_Projects.styles.css" asp-append-version="true" />
</head>

<body>
    <header>

        <div class="container">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand">WebLabsV8</a>
                <div class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </div>
                @await Component.InvokeAsync("Cart")
                <partial name="_UserPartial" />
        </div>
    </header>
    <main class="container">
        @RenderBody()
    </main>

    <footer class="fixed-bottom">
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ms-auto">
                    <a href="http://www.facebook.com" class="nav-item nav-link">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a href="http://www.vk.com" class="nav-item nav-link">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a href="http://www.twitter.com" class="nav-item nav-link">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using Lab_WT_Data.Entities;
@inject SignInManager<ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{
    <div class="dropdown ml-4 nav-color">
        <a link="#" class="dropdown-toggle" role="button" data-bs-toggle="dropdown" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img img-action="GetAvatar" img-controller="Image" width="30" alt="User" class="rounded bg-light" /> </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img img-action="GetAvatar" img-controller="Image" width="30" alt="User" class="rounded bg-light" />
                @User.Identity.Name
            </div>
            <div class="dropdown-divider"></div>
            <li><a asp-controller="Cart" asp-action="Index" class="dropdown-item">Мои товары</a></li>
            <li>
                <form asp-area="Identity" asp-page="/Account/Logout"
                    asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                    <input type="submit" value="Log off" class="dropdown-item">
                </form>
            </li>
        </ul>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li><a class="nav-item nav-link" asp-area="Identity" asp-page="/Account/Login">
                Войти
            </a></li>
        <li><a class="nav-item nav-link" asp-area="Identity" asp-page="/Account/Register">
                Зарегистрироваться
            </a></li>
    </ul>
}