Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Lab_WT_Data.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using AspNet_Projects.Extensions;
using AspNet_Projects.Models;

namespace AspNet_Projects.Controllers;
public class CartController : Controller
{
    private ApplicationDbContext _context;
    private string cartKey = "cart";
    private Cart _cart;

    public CartController(ApplicationDbContext context, Cart cart)
    {
        _context = context;
        _cart = cart;
    }
    public IActionResult Index()
    {
        _cart = HttpContext.Session.Get<Cart>(cartKey);
        return View(_cart.Items.Values);
    }
    [Authorize]
    public IActionResult Add(int id, string returnUrl)
    {
        _cart = HttpContext.Session.Get<Cart>(cartKey);
        var item = _context.Dishes.Find(id);
        if (item != null)
        {
            _cart.AddToCart(item);
            HttpContext.Session.Set<Cart>(cartKey, _cart);
        }
        return Redirect(returnUrl);
    }
}

Controllers/ProductController.cs
using Lab_WT_Data.Data;
using Microsoft.AspNetCore.Mvc;
using Lab_WT_Data.Entities;
using AspNet_Projects.Models;
using AspNet_Projects.Extensions;
using Microsoft.AspNetCore.Http;


namespace AspNet_Projects.Controllers
{
    public class ProductController : Controller
    {
        ApplicationDbContext _context;
        //private ILogger _logger;

        int _pageSize;

        public ProductController(ApplicationDbContext context/*, ILogger<ProductController> logger*/)
        {
            _pageSize = 3;
            _context = context;
            //_logger = logger;
        }
        [Route("Catalog")]
        [Route("Catalog/Page_{pageNo}")]
        public IActionResult Index(int? group, int pageNo = 1)
        {

            var dishesFiltered = _context.Dishes.Where(d => !group.HasValue || d.DishGroupId == group.Value);
            ViewData["Groups"] = _context.Groups;
            ViewData["CurrentGroup"] = group ?? 0;
            var model = ListViewModel<Dish>.GetModel(dishesFiltered, pageNo, _pageSize);
            //_logger.LogInformation($"info: group={group}, page={pageNo}");
            if (Request.IsAjaxRequest())
                return PartialView("_listpartial", model);
            else
                return View(model);
        }
    }
}

Views/Product/Index.cshtml
@model ListViewModel<Dish>

@{
    ViewData["Title"] = "Меню";

    var categories = ViewData["Groups"] as IEnumerable<DishGroup>;
    int currentGroup = (int)ViewData["CurrentGroup"];

    var text = currentGroup != 0
    ? categories
    .FirstOrDefault(g => g.DishGroupId == currentGroup)?
    .GroupName
    : "Все";

}

<div class="row">
    <div class="col-2">
        <div class="dropdown mt-2">
            <a class="btn btn-secondary dropdown-toggle" asp-action="Index" asp-controller="Product" role="button"
                id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @text
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <li><a class="dropdown-item" asp-action="Index" asp-controller="Product">Все</a></li>

                @foreach (var item in categories)
                {
                    <li>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Product"
                            asp-route-group="@item.DishGroupId" asp-route-pageNo="1">@item.GroupName</a>
                    </li>
                }
            </ul>
        </div>
    </div>
    <div class="card-group" id="list">
        <partial name="_ListPartial" model="@Model" />
    </div>


</div>

Views/Product/_ListItemPartial.cshtml
@model Dish

<div class="col">
    <div class='card h-100'>
        <img src="/Images/@Model.Image" alt='NoImage' class="card-img-top" />
        <div class="card-body">
            <h5 class="card-title">
                @Model.DishName
            </h5>
            <p class="card-text">
                @Model.Description
            </p>
            <div class="card-text badge badge-secondary text-black">
                <h6>@Model.Calories калорий</h6>
            </div>
            @{
                // Получение текущего адреса
                var request = ViewContext.HttpContext.Request;
                var returnUrl = request.Path +
                request.QueryString.ToUriComponent();
            }
            <!--Разметка кнопки добавления в корзину-->
            <p class="mt-2">
                <a asp-action="Add" asp-controller="Cart" asp-route-id="@Model.DishId" asp-route-returnUrl="@returnUrl"
                    class="btn btn-primary">
                    <i class="fa fa-shopping-cart"></i> В корзину
                </a>
            </p>
        </div>
    </div>
</div>

Views/Product/_ListPartial.cshtml
@model ListViewModel<Dish>
<div class="row row-cols-1 row-cols-md-3 g-4">

    @foreach (var item in Model)
    {
        <partial name="_ListItemPartial" model="@item" />
    }

</div>
<pager page-current="@Model.CurrentPage" page-total="@Model.TotalPages" action="Index" controller="Product"></pager>